version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      SERVER_PORT: ":8080"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: shopdb
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: "db"
    ports:
      - "8080:8080"
volumes:
  pgdata: